language: r
cache: packages
latex: false
pandoc: false
fortran: false

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: linux
      dist: trusty
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode10.3
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode7.3
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf
